<?xml version="1.0" encoding="utf-8"?><Database Name="SportStoreDB" Class="ShirtsContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0MT6QTG;Initial Catalog=SportStoreDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SportStoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.clothing" Member="clothings">
    <Type Name="clothing">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clothingType" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="clothingGender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="clothingCompany" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="clothingModel" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="clothingPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="clothingAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isClothingShort" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isClothingDrifit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="linkToClothing" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>