#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStroreWebApplication__.NET_Project.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SportStoreDB")]
	public partial class ShoesContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertShoe(Shoe instance);
    partial void UpdateShoe(Shoe instance);
    partial void DeleteShoe(Shoe instance);
    #endregion
		
		public ShoesContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SportStoreDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ShoesContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShoesContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShoesContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShoesContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Shoe> Shoes
		{
			get
			{
				return this.GetTable<Shoe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shoes")]
	public partial class Shoe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _shoeType;
		
		private string _company;
		
		private string _shoeModel;
		
		private int _shoePrice;
		
		private int _shoeAmount;
		
		private bool _isOnSall;
		
		private string _linkImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnshoeTypeChanging(string value);
    partial void OnshoeTypeChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void OnshoeModelChanging(string value);
    partial void OnshoeModelChanged();
    partial void OnshoePriceChanging(int value);
    partial void OnshoePriceChanged();
    partial void OnshoeAmountChanging(int value);
    partial void OnshoeAmountChanged();
    partial void OnisOnSallChanging(bool value);
    partial void OnisOnSallChanged();
    partial void OnlinkImageChanging(string value);
    partial void OnlinkImageChanged();
    #endregion
		
		public Shoe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoeType", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string shoeType
		{
			get
			{
				return this._shoeType;
			}
			set
			{
				if ((this._shoeType != value))
				{
					this.OnshoeTypeChanging(value);
					this.SendPropertyChanging();
					this._shoeType = value;
					this.SendPropertyChanged("shoeType");
					this.OnshoeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this.OncompanyChanging(value);
					this.SendPropertyChanging();
					this._company = value;
					this.SendPropertyChanged("company");
					this.OncompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoeModel", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string shoeModel
		{
			get
			{
				return this._shoeModel;
			}
			set
			{
				if ((this._shoeModel != value))
				{
					this.OnshoeModelChanging(value);
					this.SendPropertyChanging();
					this._shoeModel = value;
					this.SendPropertyChanged("shoeModel");
					this.OnshoeModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoePrice", DbType="Int NOT NULL")]
		public int shoePrice
		{
			get
			{
				return this._shoePrice;
			}
			set
			{
				if ((this._shoePrice != value))
				{
					this.OnshoePriceChanging(value);
					this.SendPropertyChanging();
					this._shoePrice = value;
					this.SendPropertyChanged("shoePrice");
					this.OnshoePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoeAmount", DbType="Int NOT NULL")]
		public int shoeAmount
		{
			get
			{
				return this._shoeAmount;
			}
			set
			{
				if ((this._shoeAmount != value))
				{
					this.OnshoeAmountChanging(value);
					this.SendPropertyChanging();
					this._shoeAmount = value;
					this.SendPropertyChanged("shoeAmount");
					this.OnshoeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isOnSall", DbType="Bit NOT NULL")]
		public bool isOnSall
		{
			get
			{
				return this._isOnSall;
			}
			set
			{
				if ((this._isOnSall != value))
				{
					this.OnisOnSallChanging(value);
					this.SendPropertyChanging();
					this._isOnSall = value;
					this.SendPropertyChanged("isOnSall");
					this.OnisOnSallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkImage", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string linkImage
		{
			get
			{
				return this._linkImage;
			}
			set
			{
				if ((this._linkImage != value))
				{
					this.OnlinkImageChanging(value);
					this.SendPropertyChanging();
					this._linkImage = value;
					this.SendPropertyChanged("linkImage");
					this.OnlinkImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
